version: '3.1'

# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-*/conf - configuration directory for the first build agent

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./buildserver_pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

#  teamcity:
#    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
#    ports:
#      - "8122:8111"
#    volumes:
#      - ./data_dir:/data/teamcity_server/datadir
#      - ./teamcity-server-logs:/opt/teamcity/logs
#    depends_on:
#      - db

#  teamcity-agent-php-1:
#    image: aleksxp/teamcity-agent-php
#    privileged: true
#    volumes:
#      - ./agents/agent-1/conf:/data/teamcity_agent/conf
#    environment:
#      - DOCKER_IN_DOCKER=start
#  teamcity-agent-2:
#    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
#    privileged: true
#    volumes:
#      - ./agents/agent-1/conf:/data/teamcity_agent/conf
#    environment:
#      - DOCKER_IN_DOCKER=start
#  teamcity-agent-3:
#    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
#    privileged: true
#    volumes:
#      - ./agents/agent-2/conf:/data/teamcity_agent/conf
#    environment:
#      - DOCKER_IN_DOCKER=start
