version: '3.1'

# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-*/conf - configuration directory for the first build agent

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_DATA=${PG_DATA}
    volumes:
      - ${VOLUME_BUILDSRV_PGDATA}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_EXT_PORT}:5432

  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - ${TEAMCITYSRV_EXT_PORT}:8111
    volumes:
      - ${VOLUME_DATADIR}:/data/teamcity_server/datadir
      - ${VOLUME_TEAMCITYSRV_LOGS}:/opt/teamcity/logs
    depends_on:
      - db

#  teamcity-agent-php-1:
#    image: aleksxp/teamcity-agent-php
#    privileged: true
#    volumes:
#      - ./agents/agent-1/conf:/data/teamcity_agent/conf
#    environment:
#      - DOCKER_IN_DOCKER=start
#  teamcity-agent-2:
#    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
#    privileged: true
#    volumes:
#      - ./agents/agent-1/conf:/data/teamcity_agent/conf
#    environment:
#      - DOCKER_IN_DOCKER=start
#  teamcity-agent-3:
#    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
#    privileged: true
#    volumes:
#      - ./agents/agent-2/conf:/data/teamcity_agent/conf
#    environment:
#      - DOCKER_IN_DOCKER=start
